build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$GITLAB_REGISTRY_ACCESS_TOKEN" | docker login $CI_REGISTRY -u Marko-Shevchuk --password-stdin
  script:
    - docker build -t registry.gitlab.com/modern5813345/flask_2fa_oauth .
    - docker push registry.gitlab.com/modern5813345/flask_2fa_oauth


test-job1:
  stage: test
  script:
    - echo "Running unit tests..."
    - pytest -s -v --junitxml=report.xml --cov=test_placeholder.py test_placeholder.py
    - pytest-cov --fail-under 0.5
  artifacts:
    reports:
      junit: report.xml
      cobertura: coverage.xml
    paths:
      - report.xml
      - coverage.xml


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production