build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -t registry.gitlab.com/"$CI_REGISTRY_USER"/flask-docker-multistage:latest .
    - docker push registry.gitlab.com/"$CI_REGISTRY_USER"/flask-docker-multistage:latest


test-job1:
  stage: test
  script:
    - echo "This job tests something"
#    - pip install pytest
#    - pytest test_placeholder.py

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production