build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$GITLAB_REGISTRY_ACCESS_TOKEN" | docker login $CI_REGISTRY -u Marko-Shevchuk --password-stdin
  script:
    - docker build -t registry.gitlab.com/modern5813345/flask_2fa_oauth .
    - docker push registry.gitlab.com/modern5813345/flask_2fa_oauth


test-job1:
  stage: test
  script:
    - echo "This job tests something"
#    - pip install pytest
#    - pytest test_placeholder.py

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production